path:
  ckpt_path: "./output/ckpt/papareo"
  log_path: "./output/log/papareo"
  result_path: "./output/result/papareo"
optimizer:
  batch_size: 128 #196=max for 80GB
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.005
  step_size: 0.0025
  grad_clip_thresh: 1.0
  grad_acc_step: 1
step:
  total_step: 100000
  log_step: 50
  synth_step: 200
  val_step: 200
  save_step: 1000
