path:
  ckpt_path: "./output/ckpt/papareo"
  log_path: "./output/log/papareo"
  result_path: "./output/result/papareo"
optimizer:
  batch_size: 96
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 500
  anneal_steps: [25000, 40000, 50000]
  anneal_rate: 0.3
step:
  total_step: 50000
  log_step: 100
  synth_step: 400
  val_step: 400
  save_step: 2500